#########################################################################
# Title:         Saltbox: OpenLDAP Role                                 #
# Author(s):     salty                                                  #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: Wait for 60 seconds
  ansible.builtin.wait_for:
    timeout: 60

- name: Make sure we have a parent entry for users
  community.general.ldap_entry:
    dn: "ou={{ item }},dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    objectClass: "organizationalUnit"
    server_uri: "ldap://openldap/"
    bind_dn: "cn=admin,dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    bind_pw: "{{ user.pass }}"
  with_items:
    - "people"
    - "groups"

- name: Make sure we have a parent entry for users
  community.general.ldap_entry:
    dn: "cn={{ item.key }},ou=groups,dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    objectClass:
      - "posixGroup"
      - "top"
    attributes:
      gidnumber: "{{ item.value }}"
    server_uri: "ldap://openldap/"
    bind_dn: "cn=admin,dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    bind_pw: "{{ user.pass }}"
  with_dict:
    admins: 500
    users: 501

- name: Generate Password Hash
  ansible.builtin.shell: "echo {{ user.pass }} | openssl passwd -6 -stdin"
  register: ldap_user_hash

- name: Make sure we have a parent entry for users
  community.general.ldap_entry:
    dn: "cn={{ user.name }},ou=people,dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    objectClass:
      - "inetOrgPerson"
      - "posixAccount"
      - "top"
    attributes:
      description: Saltbox Admin User
      userPassword: "{CRYPT}{{ ldap_user_hash.stdout }}"
      sn: "{{ user.name }}"
      uid: "{{ user.name }}"
      uidnumber: "1000"
      gidnumber: "500"
      homedirectory: "/home/users/{{ user.name }}"
      loginshell: /bin/bash
    server_uri: "ldap://openldap/"
    bind_dn: "cn=admin,dc={{ authelia_domain.stdout }},dc={{ authelia_tld.stdout }}"
    bind_pw: "{{ user.pass }}"
