#########################################################################
# Title:         Saltbox: ruTorrent | Default Variables                 #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
################################
# Basics
################################

rutorrent_name: rutorrent

################################
# Paths
################################

rutorrent_paths_folder: "{{ rutorrent_name }}"
rutorrent_paths_location: "{{ server_appdata_path }}/{{ rutorrent_paths_folder }}"
rutorrent_paths_downloads_location: "{{ downloads_torrents_path }}/{{ rutorrent_paths_folder }}"
rutorrent_paths_folders_list:
  - "{{ rutorrent_paths_location }}"
  - "{{ rutorrent_paths_location }}/data"
  - "{{ rutorrent_paths_location }}/overrides"
  - "{{ rutorrent_paths_location }}/passwd"
  - "{{ rutorrent_paths_downloads_location }}"
  - "{{ rutorrent_paths_downloads_location }}/completed"
  - "{{ rutorrent_paths_downloads_location }}/incomplete"
  - "{{ rutorrent_paths_downloads_location }}/watched"

################################
# Web
################################

rutorrent_web_subdomain: "{{ rutorrent_name }}"
rutorrent_web_domain: "{{ user.domain }}"
rutorrent_web_port: "8080"
rutorrent_web_url: "{{ 'https://' + rutorrent_web_subdomain + '.' + rutorrent_web_domain
                    if (reverse_proxy_is_enabled)
                    else 'http://localhost:' + rutorrent_web_port }}"

################################
# DNS
################################

rutorrent_dns_record: "{{ rutorrent_web_subdomain }}"
rutorrent_dns_zone: "{{ rutorrent_web_domain }}"
rutorrent_dns_proxy: "{{ dns.proxied }}"

################################
# Traefik
################################

rutorrent_traefik_sso_middleware: "{{ traefik_default_sso_middleware }}"

rutorrent_traefik_middleware_default: "{{ traefik_default_middleware + ','
                                          + lookup('vars', rutorrent_name + '_traefik_sso_middleware', default=rutorrent_traefik_sso_middleware)
                                       if (lookup('vars', rutorrent_name + '_traefik_sso_middleware', default=rutorrent_traefik_sso_middleware) | length > 0)
                                       else traefik_default_middleware }}"
rutorrent_traefik_middleware_custom: ""
rutorrent_traefik_middleware: "{{ rutorrent_traefik_middleware_default + ','
                                  + rutorrent_traefik_middleware_custom
                               if (not rutorrent_traefik_middleware_custom.startswith(',') and rutorrent_traefik_middleware_custom | length > 0)
                               else rutorrent_traefik_middleware_default
                                  + rutorrent_traefik_middleware_custom }}"
rutorrent_traefik_certresolver: "{{ traefik_default_certresolver }}"
rutorrent_traefik_enabled: true

################################
# Config
################################

rutorrent_config_memory_limit: "256M"
rutorrent_config_upload_max_size: "16M"
rutorrent_config_opcache_mem_size: "128"
rutorrent_config_max_file_uploads: "50"
rutorrent_config_real_ip_from: "172.19.0.0/16"
rutorrent_config_xmlrpc_size_limit: "1M"
rutorrent_config_webdav_port: "9000"
rutorrent_config_ru_remove_core_plugins: "erasedata,httprpc"
rutorrent_config_ru_save_uploaded_torrents: "true"
rutorrent_config_ru_overwrite_uploaded_torrents: "false"

################################
# THEME
################################

# Options can be found at https://github.com/gilbN/theme.park
rutorrent_themepark_enabled: false
rutorrent_themepark_theme: "{{ global_themepark_theme }}"
rutorrent_themepark_domain: "{{ global_themepark_domain }}"

################################
# Docker
################################

# Container
rutorrent_docker_container: "{{ rutorrent_name }}"

# Image
rutorrent_docker_image_pull: true
rutorrent_docker_image_tag: "latest"
rutorrent_docker_image: "crazymax/rtorrent-rutorrent:{{ rutorrent_docker_image_tag }}"

# Ports
rutorrent_docker_ports_51413: "{{ port_lookup_51413.port
                               if (port_lookup_51413.port is defined)
                                  and (port_lookup_51413.port | trim | length > 0)
                               else '51413' }}"
rutorrent_docker_ports_9000: "{{ port_lookup_9000.port
                              if (port_lookup_9000.port is defined)
                                  and (port_lookup_9000.port | trim | length > 0)
                              else '9000' }}"
rutorrent_docker_ports_6881: "{{ port_lookup_6881.port
                              if (port_lookup_6881.port is defined)
                                  and (port_lookup_6881.port | trim | length > 0)
                              else '6881' }}"

rutorrent_docker_ports_defaults:
  - "{{ rutorrent_docker_ports_51413 }}:{{ rutorrent_docker_ports_51413 }}"
  - "{{ rutorrent_docker_ports_51413 }}:{{ rutorrent_docker_ports_51413 }}/udp"
  - "{{ rutorrent_docker_ports_9000 }}:{{ rutorrent_config_webdav_port }}"
  - "{{ rutorrent_docker_ports_6881 }}:{{ rutorrent_docker_ports_6881 }}/udp"
rutorrent_docker_ports_ui:
  - "{{ rutorrent_web_port }}:{{ rutorrent_web_port }}"
rutorrent_docker_ports_custom: []

rutorrent_docker_ports: "{{ rutorrent_docker_ports_defaults
                            + rutorrent_docker_ports_ui
                            + rutorrent_docker_ports_custom
                         if (not reverse_proxy_is_enabled)
                         else rutorrent_docker_ports_defaults
                            + rutorrent_docker_ports_custom }}"

# Envs
rutorrent_docker_envs_default:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  WAN_IP: "{{ ip_address_public }}"
  MEMORY_LIMIT: "{{ rutorrent_config_memory_limit }}"
  UPLOAD_MAX_SIZE: "{{ rutorrent_config_upload_max_size }}"
  OPCACHE_MEM_SIZE: "{{ rutorrent_config_opcache_mem_size }}"
  MAX_FILE_UPLOADS: "{{ rutorrent_config_max_file_uploads }}"
  REAL_IP_FROM: "{{ rutorrent_config_real_ip_from }}"
  WEBDAV_PORT: "{{ rutorrent_config_webdav_port }}"
  RT_DHT_PORT: "{{ rutorrent_docker_ports_6881 }}"
  RT_INC_PORT: "{{ rutorrent_docker_ports_51413 }}"
  RU_REMOVE_CORE_PLUGINS: "{{ rutorrent_config_ru_remove_core_plugins }}"
  RU_SAVE_UPLOADED_TORRENTS: "{{ rutorrent_config_ru_save_uploaded_torrents }}"
  RU_OVERWRITE_UPLOADED_TORRENTS: "{{ rutorrent_config_ru_overwrite_uploaded_torrents }}"
  TP_DOMAIN: "{{ rutorrent_themepark_domain }}"
  TP_THEME: "{{ rutorrent_themepark_theme }}"
rutorrent_docker_envs_custom: {}
rutorrent_docker_envs: "{{ rutorrent_docker_envs_default
                           | combine(rutorrent_docker_envs_custom) }}"

# Commands
rutorrent_docker_commands_default: []
rutorrent_docker_commands_custom: []
rutorrent_docker_commands: "{{ rutorrent_docker_commands_default
                               + rutorrent_docker_commands_custom }}"

# Volumes
rutorrent_docker_volumes_default:
  - "{{ rutorrent_paths_location }}/data:/data"
  - "{{ rutorrent_paths_location }}/passwd:/passwd"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "{{ rutorrent_paths_location }}/overrides/.rtlocal.rc:/tpls/etc/rtorrent/.rtlocal.rc"
rutorrent_docker_volumes_custom: []
rutorrent_docker_volumes_theme:
  - "{{ rutorrent_paths_location }}/98-themepark:/etc/cont-init.d/98-themepark"
rutorrent_docker_volumes: "{{ rutorrent_docker_volumes_default
                              + rutorrent_docker_volumes_custom
                           if not (rutorrent_themepark_enabled)
                           else rutorrent_docker_volumes_default
                              + rutorrent_docker_volumes_custom
                              + rutorrent_docker_volumes_theme }}"

# Devices
rutorrent_docker_devices_default: []
rutorrent_docker_devices_custom: []
rutorrent_docker_devices: "{{ rutorrent_docker_devices_default
                              + rutorrent_docker_devices_custom }}"

# Hosts
rutorrent_docker_hosts_default: []
rutorrent_docker_hosts_custom: []
rutorrent_docker_hosts: "{{ docker_hosts_common
                            | combine(rutorrent_docker_hosts_default)
                            | combine(rutorrent_docker_hosts_custom) }}"

# Labels
rutorrent_docker_labels_default: {}
rutorrent_docker_labels_custom: {}
rutorrent_docker_labels: "{{ docker_labels_common
                             | combine(rutorrent_docker_labels_default)
                             | combine(rutorrent_docker_labels_custom) }}"

# Hostname
rutorrent_docker_hostname: "{{ rutorrent_name }}"

# Networks
rutorrent_docker_networks_alias: "{{ rutorrent_name }}"
rutorrent_docker_networks_default: []
rutorrent_docker_networks_custom: []
rutorrent_docker_networks: "{{ docker_networks_common
                               + rutorrent_docker_networks_default
                               + rutorrent_docker_networks_custom }}"

# Capabilities
rutorrent_docker_capabilities_default: []
rutorrent_docker_capabilities_custom: []
rutorrent_docker_capabilities: "{{ rutorrent_docker_capabilities_default
                                   + rutorrent_docker_capabilities_custom }}"

# Security Opts
rutorrent_docker_security_opts_default: []
rutorrent_docker_security_opts_custom: []
rutorrent_docker_security_opts: "{{ rutorrent_docker_security_opts_default
                                    + rutorrent_docker_security_opts_custom }}"

# Restart Policy
rutorrent_docker_restart_policy: unless-stopped

# Stop Timeout
rutorrent_docker_stop_timeout: 900

# State
rutorrent_docker_state: started
