##########################################################################
# Title:         Saltbox: MariaDB | Default Variables                    #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

mariadb_name: mariadb

################################
# Paths
################################

mariadb_paths_folder: "{{ mariadb_name }}"
mariadb_paths_location: "{{ server_appdata_path }}/{{ mariadb_paths_folder }}"
mariadb_paths_folders_list:
  - "{{ mariadb_paths_location }}"

################################
# Settings
################################

mariadb_docker_env_password: "password4321"
mariadb_docker_env_user: "{{ user.name }}"
mariadb_docker_env_db: "saltbox"

################################
# Docker
################################

# Container
mariadb_docker_container: "{{ mariadb_name }}"

# Image
mariadb_docker_image_pull: true
mariadb_docker_image_tag: "10"
mariadb_docker_image: "mariadb:{{ mariadb_docker_image_tag }}"

# Ports
mariadb_docker_ports_defaults: []
mariadb_docker_ports_custom: []
mariadb_docker_ports: "{{ mariadb_docker_ports_defaults
                          + mariadb_docker_ports_custom }}"

# Envs
mariadb_docker_envs_default:
  TZ: "{{ tz }}"
  MARIADB_ROOT_PASSWORD: "{{ mariadb_docker_env_password }}"
  MARIADB_USER: "{{ mariadb_docker_env_user }}"
  MARIADB_DATABASE: "{{ mariadb_docker_env_db }}"
mariadb_docker_envs_custom: {}
mariadb_docker_envs: "{{ mariadb_docker_envs_default
                         | combine(mariadb_docker_envs_custom) }}"

# Commands
mariadb_docker_commands_default: []
mariadb_docker_commands_custom: []
mariadb_docker_commands: "{{ mariadb_docker_commands_default
                             + mariadb_docker_commands_custom }}"

# Volumes
mariadb_docker_volumes_default:
  - "{{ mariadb_paths_location }}:/var/lib/mysql"
mariadb_docker_volumes_custom: []
mariadb_docker_volumes: "{{ mariadb_docker_volumes_default
                            + mariadb_docker_volumes_custom }}"

# Devices
mariadb_docker_devices_default: []
mariadb_docker_devices_custom: []
mariadb_docker_devices: "{{ mariadb_docker_devices_default
                            + mariadb_docker_devices_custom }}"

# Hosts
mariadb_docker_hosts_default: []
mariadb_docker_hosts_custom: []
mariadb_docker_hosts: "{{ docker_hosts_common
                          | combine(mariadb_docker_hosts_default)
                          | combine(mariadb_docker_hosts_custom) }}"

# Labels
mariadb_docker_labels_default: {}
mariadb_docker_labels_custom: {}
mariadb_docker_labels: "{{ docker_labels_common
                           | combine(mariadb_docker_labels_default)
                           | combine(mariadb_docker_labels_custom) }}"

# Hostname
mariadb_docker_hostname: "{{ mariadb_name }}"

# Networks
mariadb_docker_networks_alias: "{{ mariadb_name }}"
mariadb_docker_networks_default: []
mariadb_docker_networks_custom: []
mariadb_docker_networks: "{{ docker_networks_common
                             + mariadb_docker_networks_default
                             + mariadb_docker_networks_custom }}"

# Capabilities
mariadb_docker_capabilities_default: []
mariadb_docker_capabilities_custom: []
mariadb_docker_capabilities: "{{ mariadb_docker_capabilities_default
                                 + mariadb_docker_capabilities_custom }}"

# Security Opts
mariadb_docker_security_opts_default: []
mariadb_docker_security_opts_custom: []
mariadb_docker_security_opts: "{{ mariadb_docker_security_opts_default
                                  + mariadb_docker_security_opts_custom }}"

# Restart Policy
mariadb_docker_restart_policy: unless-stopped

# State
mariadb_docker_state: started

# User
mariadb_docker_user: "{{ uid }}:{{ gid }}"
