##########################################################################
# Title:         Saltbox: Authelia | Domain Tasks                        #
# Author(s):     salty                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
- name: Install tld python package
  ansible.builtin.pip:
    name: tld
    executable: pip3

- name: Get FLD
  ansible.builtin.shell: |
    python3 -c "from tld import get_tld; res = get_tld(\"http://{{ authelia_web_domain | default(user.domain) }}\", as_object=True); print(res.tld)"
  register: authelia_tld

- name: Get FLD
  ansible.builtin.shell: |
    python3 -c "from tld import get_tld; res = get_tld(\"http://{{ authelia_web_domain | default(user.domain) }}\", as_object=True); print(res.domain)"
  register: authelia_domain
